### ISSUE TITLE
SourceTree update breaks hack

### ISSUE THREAD

**Issue by therightstuff** [nitrix/sourcetree-vm-hack#1] opened 2015-07-15 17:36 UTC
Hey :)

I made the mistake of updating to SourceTree 1.6.17 and the vagrant's git is no longer accessible by SourceTree. I reverted to http://downloads.atlassian.com/software/sourcetree/windows/SourceTreeSetup_1.6.14.exe and it works just fine now...

**Comment by nitrix** [comment] 2015-07-17 14:52
@therightstuff  I'll investigate during lunch today. Sorry for the delayed response.

**Comment by therightstuff** [comment] 2015-07-18 01:52
thanks! have a great one :)

**Comment by therightstuff** [comment] 2015-08-03 15:11
hi! sorry to be annoying, but did you figure out what the problem is yet?

**Comment by nitrix** [comment] 2015-08-05 19:20
I was unable to reproduce it at home, but a known problem is that updating SourceTree could indirectly override the hack with a newer version of the Git executale.

Can you confirm that removing and reinstalling the hack after updating to the newer SourceTree version still doesn't work?

**Comment by nitrix** [comment] 2015-08-05 19:38
This ticket has been hitting my OCD very aggressively for the past days. The sooner I can close it, the better :P

**Comment by therightstuff** [comment] 2015-08-12 20:43
Hi - sorry about the delay on my end, I'm not in the office for a few weeks so I won't be able to retest. I did follow through very carefully with uninstalling the hack and completely uninstalling and reinstalling sourcetree before reinstalling the hack and it didn't work: I actually went through this a few times to make sure. Have you been testing with versions later than .17? If so, perhaps they un-broke something...

**Comment by therightstuff** [comment] 2015-09-14 16:50
Hi - so I'm back in the office and have just installed the latest version of SourceTree with the same result: 
![image](https://cloud.githubusercontent.com/assets/1819425/9855871/0b32fb3c-5adf-11e5-9ee4-deb3b0ccf506.png)
Could it be a configuration issue?

**Comment by nitrix** [comment] 2015-09-17 03:49
That's messed up, it's a path issue. It's supposed to look into the install path (of where the sourcetree executable is located) to find its config (git.conf), not where it's currently running (the mounted repository).

I think it's time for a little rewrite. Allow me a few days.

**Comment by nitrix** [comment] 2015-11-24 20:34
Fixed on version 1.7

**Closed by nitrix** 2015-11-24 20:34 UTC
Labels: bug

**Comment by therightstuff** [comment] 2015-11-24 22:59
awesome - thank you!!
